name: Tag on Master

on:
  push:
    branches:
      - master

env:
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get the latest tag from GitHub
        id: get_latest_tag
        run: |
          git fetch --tags
          echo "::set-output name=latest_tag::$(git describe --abbrev=0 --tags)"

      - name: Determine next tag
        id: next_tag
        run: |
          # Get the latest tag from the previous step
          latest_tag=${{ steps.get_latest_tag.outputs.latest_tag }}
          
          # Extract the numeric part of the tag (e.g., 0.1.5 -> 5)
          numeric_part=$(echo $latest_tag | cut -d '.' -f 3)
          
          # Increment the numeric part
          next_numeric_part=$((numeric_part + 1))
          
          # Create the next tag (e.g., 0.1.5 -> 0.1.6)
          next_tag=$(echo $latest_tag | sed "s/$numeric_part$/$next_numeric_part/")
          
          echo "::set-output name=next_tag::$next_tag"

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git config --global credential.helper '!f() { sleep 1; echo "username=github-actions[bot]"; echo "password=${ACCESS_TOKEN}"; }; f'

      - name: Create tag
        run: |
          TAG=${{ steps.next_tag.outputs.next_tag }}
          git tag $TAG
          git push origin $TAG
